### ISSUE TITLE
Match any file in a project

### ISSUE THREAD

**Issue by abdulhaq-e** [Osmose/advanced-open-file#114]
Thanks for the package. It really makes working with atom more efficient. 

In emacs, there is a similar packages that opens ("finds") any file in the current project _without_ switching to the file's directory. Is it possible to implement this?

**Comment by Osmose** [comment]
That sounds like the [fuzzy-finder package](https://github.com/atom/fuzzy-finder), which is a core package included with Atom by default. Is that what you're thinking of?

**Comment by abdulhaq-e** [comment]
Exactly! I missed it somehow. But now, what is the difference between the two packages?

**Comment by Osmose** [comment]
The fuzzy-finder can only find files inside of projects you have open; advanced-open-file can access files anywhere on the filesystem. Also, you can see the contents of a particular path in advanced-open-file, whereas fuzzy-finder is really about locating a single file. For me personally, I work on Django projects, which have lots of `models.py` files, and if I'm trying to find the `models.py` for a particular part of the project that I'm working on, it's often easier for me to use advanced-open-file than it is to remember the set of directories to filter out other `models.py` files from across the project.

It's a ton of little things, and there's a bit of overlap. But people seem to like it. :D

Closing this since another package provides this functionality already. Thanks!
