### ISSUE TITLE
Issue listing files on windows

### ISSUE THREAD

**Issue by NuclearCookie** [Osmose/advanced-open-file#13]
Hi, If I'm on windows I have troubles listing the file content of the current directory. It looks like it's related to the windows style paths. For example:

C:\Projects\TestProject will list nothing, where \Projects\TestProject will show all directories..

**Comment by Osmose** [comment]
@NuclearCookie This is closed because 5bcf12d landed, but if you're still having issues, could you please reopen with info on which version of windows and what kind of paths you're having trouble opening?

**Comment by Osmose** [comment]
Oh yeah. I forgot to ask.

@Traverse, have you even seen any issues similar to this?

**Comment by Traverse** [comment]
Yes I did have similar issues also this was directly related to #21 since by default it was using the full windows path `C:\Projects\TestProject` which meant there were no directories being listed and thus tab auto-completion wouldn't work because you can't tab complete non-existent paths, `\Projects\TestProject` did list all the directories and thus tab auto-completion worked. So the issues were kind of intertwined.

**Comment by Osmose** [comment]
`\Projects\TestProject` works? That's surprising to me, I would've expected that it needed the `C:\`. I need to look up exactly how windows paths work in Node.

**Comment by NuclearCookie** [comment]
Hey sorry for the inactivity. I'll see if I can test it today but I guess it's going to be fine ;)

**Comment by NuclearCookie** [comment]
All good, thanks! :+1:
