### ISSUE TITLE
Tab completing a directory should include the slash

### ISSUE THREAD

**Issue by crossman** [Osmose/advanced-open-file#20]
I just switched over from advanced-new-file and was trying to create a new file. I hit tab to complete the folder path and it didn't fill in the trailing slash, so my list of suggestions didn't update. It doesn't seem to offer any functionality at that level either because I can't hit enter to open the directory. It's a little less productive to have to hit tab + / rather than just tab to select a directory and advance to the next level.

**Comment by Osmose** [comment]
Thanks for the bug report!

Hmmm, it should add the extra slash, and it does for me. I have a few questions to try and narrow this down:

- What path are you trying to complete? 
- Also, what's the folder structure that you're testing this out on? Any weird permissions to look out for?
- Finally, are you on Windows, Linux, or OSX?

**Comment by crossman** [comment]
Sorry you can disregard this one. It was totally my fault, it didn't add the slash for me because there was a file that shared the folder name. So I was trying to tab into the `test/` folder and I also had a file called `test.config.js`. Has that behavior changed? Because I've had these files in here for months and never ran into that with it when I was using advanced-new-file.

**Comment by Osmose** [comment]
Aha! That'd do it.

Advanced-new-file only considered folders for autocomplete because it only cared about creating new files, unless you had a preference enabled for showing files in autocomplete. I imagine you had the preference disabled.

Because advanced-open-file cares about both creating and opening, I removed the setting as it seemed unnecessary and made the code more complex, and it also seems more consistent with autocomplete on the shell. I hope removing that setting doesn't inconvenience you too much!

**Comment by crossman** [comment]
Makes sense. I would love to have the option of ignoring files because I find that cmd+t generally works well for me for opening files and I mostly use this creating new files.
