### ISSUE TITLE
Unneed of option ..

### ISSUE THREAD

**Issue by terraqout** [Osmose/advanced-open-file#34]
When opening file you always see double dots moving you to up directory. If maintainer think this is a great capability, please change order so you need not to scroll one time to select file.
**NOW**
prompt: /path/to/project/package.json

list: 
..
package.json

**SHOULD BE**
prompt: /path/to/project/package
list:
package.json
..

p.s. regexp matches appreciated to.

**Comment by Osmose** [comment]
Thanks for the suggestion!

How does this sound: If listing the contents of a directory with nothing being auto-completed, show the `..`. If the list is being filtered by the autocomplete, hide the `..`.

So if the current input is `/path/to/project/` you'd see the `..` at the top because it's just listing the contents of the directory, but if it is `/path/to/project/package`, the `..` is hidden, since the listing is being filtered by the `package` input.

That sounds like a good way to work to me, and I _think_ it covers your use case. Thoughts?

**Comment by terraqout** [comment]
Yeap, it would be great
