### ISSUE TITLE
Unable to work with in dev mode

### ISSUE THREAD

**Issue by artagnon** [Osmose/advanced-open-file#42]
dev mode throws this error:

  Cannot find module 'atom-space-pen-views'

I know the module is deprecated, but how is it working in normal mode?

**Comment by Osmose** [comment]
@artagnon You need to run `npm install` within the development checkout to get it to download the dependencies. `apm install` might work too but I'm not 100% sure because I think they co-opted that to mean "install this package into atom" instead of "install the dependencies of this package to node_modules".

Which reminds me, I should probably document developer setup. :P

Does that solve your problem?

**Comment by artagnon** [comment]
Ah, I guess that counts as common sense. Sorry, I'm new to Atom/Node.js: just started using it yesterday.

Thanks.

**Comment by Osmose** [comment]
> Ah, I guess that counts as common sense. Sorry, I'm new to Atom/Node.js: just started using it yesterday.

No worries! I wouldn't actually call it common sense, and the docs for working on atom packages are only kind've okay; I had to figure out the npm install thing myself after messing it up multiple times.

I filed #47 to deal with writing docs for getting a dev setup going.
