### ISSUE TITLE
Create/open multiple files

### ISSUE THREAD

**Issue by alekmych** [Osmose/advanced-open-file#54]
Something like "/path/[file.one,file.two]" would be helpful.

**Comment by Osmose** [comment]
Thanks for the suggestion. advanced-new-file used to have a feature like this, but I removed because it's a bit too complex both implementation-wise and UX-wise and I don't think it's a compelling feature to make that worth it.

Like, what do we show when the user is typing in the paths? What if files have `[` or `]` in their filenames? Do we detect which of the comma-separated paths the cursor is in and show the listing for that directory?

In the end all it really saves you is having to type the prefixed path multiple times, which project folders or copy/paste can do for you easily anyway.

So I'm not interested in adding this feature, but thanks again for the suggestion!
