### ISSUE TITLE
~/ not working on mac

### ISSUE THREAD

**Issue by pimentel** [Osmose/advanced-open-file#60]
I am on atom 1.0.19 on os x Yosemite.

When I open the dialogue (cmd-alt-o) and enter `~/` there are no files listed. If I manually enter a path, (e.g. ~/.atom) no files are still listed. I have tried setting the default directory to all the different options (current working directory, no directory) and I get the same result. I can see the directory if I give the full path (e.g. /Users/hjp/.atom).

Please let me know if there is any additional information I can give to help.

Thanks for the hard work. It is a very cool package

**Comment by Osmose** [comment]
I'll need a bit more time to confirm, but my initial guess is that the functions we use for reading directories don't auto-convert `~` into the home directory. I imagine we haven't heard of this bug before since people enable the fast directory switching shortcuts, which will automatically convert the `~`.

For now you can enable that setting and it should work well enough for your purposes. In the long run I think it's probably good for us to support `~` and `..` without the setting on (and just have them work without replacing them), but I'll have to think on it some more.

**Comment by pimentel** [comment]
duh! somehow I missed fast directory switching. it works great like that!

thanks again.

**Comment by Osmose** [comment]
This should be fixed on master and will be released with the next update. Thanks again for the report!
