### ISSUE TITLE
Setting to override Command-O

### ISSUE THREAD

**Issue by ianb** [Osmose/advanced-open-file#73]
I'm too lazy to figure out keyboard shortcuts in Atom, or maintain them; it would be cool if there was a pref for the package to override Command-O (because the system open dialog is too dumb to ever be useful, but I am used to the keyboard shortcut).

If you tell me I'm being *too* lazy I won't feel offended.

**Comment by Osmose** [comment]
Thanks for the suggestion!

Having a pref is a bit much, nor am I even sure if it's possible without hackery or being on by default (as keybindings are specified in https://github.com/Osmose/advanced-open-file/blob/master/keymaps/advanced-open-file.cson rather than, say, registered via JS).

The README has an example of binding to Ctrl+X Ctrl+F which you can copy and paste and replace with Cmd+O which should work, and finding the file to edit is as simple as using the menu Atom -> Open Your Keymap.

So I guess I'm saying you're _too_ lazy. BUT DON'T CHANGE YOU BEAUTIFUL JUST THE WAY YOU IS
