### ISSUE TITLE
Merge with advanced new file

### ISSUE THREAD

**Issue by Trudko** [Osmose/advanced-open-file#8]
Hi :),

how about merging advanced new file and advanced open file? I don't have much time to take care of advanced new file so I would be happy if you could maintain it.

**Comment by Osmose** [comment]
I'm down for that!

What's unclear to me is how to merge the two packages so users of either one end up on the same project. I posted https://discuss.atom.io/t/merging-packages/19281 asking about it, but it now occurs to me that you might know how to achieve this or have an opinion on what should happen and I should've asked you directly first. Whoops!

**Comment by Trudko** [comment]
Sure so how exactly would you wanna do that? I think we should stick to advanced new file simply because that has more people right AFAIK. Are you ok with that?

**Comment by Osmose** [comment]
The only thing stopping me is the name; it took me _ages_ to find and notice advanced-new-file because I was looking for a way to open files, not just create new ones. Had it said anything about opening files I would have installed it much sooner and been much happier. :D

How about this then: we publish a new version of advanced-new-file that shows a one-time prompt to switch with an install button that runs apm (it was pointed out in the thread that [package-sync](https://github.com/lee-dohm/package-sync/blob/master/lib/package-sync.coffee#L72) does this) and installs advanced-open-file and removes advanced-new-file? I can play around with that if you think it's a good plan.

**Comment by Trudko** [comment]
How about to create something like advanced file maybe?

**Comment by Osmose** [comment]
Renaming doesn't really solve the issue of getting the users of both packages on the same package.

If you're curious about what the users think, go for it! In either case I still think the plan I suggested above is a decent option for keeping open in the name and unifying the users. Is there something you don't like about it?

**Comment by eboracus** [comment]
As one of the download statistics on both packages (:D) I agree this would be a good idea.

I agree that going for the name advanced-open-file (open representing open-new and open-existing) and following roughly along the lines of what was suggested in that thread seems a reasonable plan, that should work.

**Comment by Trudko** [comment]
Yeah I think lets go with this :) So what would be the plan ? :)

**Comment by Osmose** [comment]
> Yeah I think lets go with this :) So what would be the plan ? :)

I can find some time this week to work on a PR to advanced-new-file. You can review, then once it's all good, publish and we're done!

**Comment by Trudko** [comment]
cool! :)

**Comment by Osmose** [comment]
@Trudko Thanks for merging my patch! Is there anything else you need help with before releasing it?

**Comment by Trudko** [comment]
Finally published :) sorry it took so long.

**Comment by Osmose** [comment]
Woo! :+1:
