### ISSUE TITLE
Feature request: Multiple selection

### ISSUE THREAD

**Issue by ericdill** [Osmose/advanced-open-file#91]
Hi Osmose,

(Feel's weird to use your actual name in the greeting since I've never actually met you, even though it is on your GH page...)

This is probably my most-used package in Atom :fireworks: .  Thanks for writing and maintaining this!

A number of times now, I have found myself wanting to open a number of folders at the same time through the advanced-open-file interface.  Do you think it would be possible to add the ability to select multiple lines at the same time and then dispatch that to the `application:add-project-folder` command?  If this is outside the scope of advanced-open-file, I sure understand!

Thanks!

[edit] I suppose it would also be worthwhile to dispatch that to the `pane:split-<direction>` and `core:confirm`

**Comment by Osmose** [comment]
Thanks for the suggestion and kind words! :D

advanced-new-file used to have something kind've like this, but it was based on using a weird path separator and typing in multiple paths. It was awkward, but mostly because of that path thing, I think.

That's the main sticking point for me, though. I think it's a very good thing that more or less everything advanced-open-file does revolves around the path in the textarea. It makes reasoning about its state very straightforward; everything can be determined by that path. 

I imagine that's why the multiple path thing was added to advanced-new-file in the first place; selecting multiple things outside of the textarea suddenly adds a new piece of state that needs to be considered, but using the path separators combines it all into a single stateful piece again.

I'm leaning towards no on this. Sorry about that, but thanks again for using the package!

**Comment by ericdill** [comment]
> I think it's a very good thing that more or less everything advanced-open-file does revolves around the path in the textarea. It makes reasoning about its state very straightforward; everything can be determined by that path.

That makes total sense.  Thanks for the clear response, even though the answer was "no"!
