### ISSUE TITLE
automatically 'Add project folder'

### ISSUE THREAD

**Issue by dagolinuxoid** [Osmose/advanced-open-file#93]
Once a needed file has opened in order to see tree structure you have to invoke add-project-folder via palette or through ctrl-o. I think it would be useful to add option in advanced-open-file settings : automatically add project folder its opened file as if we open this file by shell (terminal) $ atom name-file.

**Comment by Osmose** [comment]
Thanks for the suggestion!

I'm not a fan of having a setting that opens a file/directory as a project folder because I don't think that behavior is expected or common. You'd have to toggle it off and on constantly or have a TON of project folders open.

But maybe instead we can make the "open project folder" action not automatically close the dialog? That way, if you want to open a project folder _and_ a file, you can just open the project folder and then continue navigating to the file you want to open. But people who just want to open a file aren't forced into opening project folders or toggling a preference all the time.

Does that sound like it would handle your use case?

**Comment by dagolinuxoid** [comment]
Heck, yeah)). Definitely it sounds good!
ctrl+alt+o > /home/linux/web-project/ for example and than hitting enter will open the project folder in the tree.

**Comment by Osmose** [comment]
Fixed in master, this should be released sometime within the next week. :D

**Comment by dagolinuxoid** [comment]
CooL :clap:

**Comment by Osmose** [comment]
Released! https://github.com/Osmose/advanced-open-file/releases/tag/v0.14.3

**Comment by dagolinuxoid** [comment]
Yep )), but hitting enter after  `/home/linux/Templates/atompen/` for example do nothing; it supposed to open this (atompen) folder as a project, right?

**Comment by Osmose** [comment]
Nah, there's a separate keyboard shortcut for opening files as project folders. It's `Shift-Cmd-O`/`Ctrl-Alt-O` by default.
